Repository 9oormthon-univ/2024_DANPOONG_TEAM_23_FE, pull requests merged in 2024-11, with the labels that each got.

#2 feat: 프로젝트 생성 및 초기 설정
  .gitignore
  .husky/commit-msg
  .husky/pre-commit
  README.md
  commitlint.config.js
  eslint.config.js
  index.html
  lint-staged.config.js
  package.json
  pnpm-lock.yaml
  postcss.config.js
  prettier.config.js
  public/.gitkeep
  src/assets/.gitkeep
  src/components/.gitkeep
  src/main.tsx
  src/routes/root.tsx
  src/styles/globals.css
  src/utils/.gitkeep
  src/vite-env.d.ts
  tailwind.config.js
  tsconfig.app.json
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: enhancement

#5 feat: 프로젝트 SVG 설정
  package.json
  pnpm-lock.yaml
  src/vite-env.d.ts
  svg.d.ts
  tsconfig.app.json
  vite.config.ts
Labels: enhancement

#6 feat: 디자인 시스템 구축
  README.md
  index.html
  package.json
  pnpm-lock.yaml
  public/.gitkeep
  public/favicon.svg
  src/assets/.gitkeep
  src/assets/svgs/arrow-right.svg
  src/assets/svgs/bottom-navigation-floor.svg
  src/assets/svgs/calendar.svg
  src/assets/svgs/chevron-down.svg
  src/assets/svgs/chevron-left.svg
  src/assets/svgs/chevron-up.svg
  src/assets/svgs/delete.svg
  src/assets/svgs/female.svg
  src/assets/svgs/home.svg
  src/assets/svgs/logout.svg
  src/assets/svgs/male.svg
  src/assets/svgs/phone.svg
  src/assets/svgs/place.svg
  src/assets/svgs/setting.svg
  src/assets/svgs/star.svg
  src/assets/svgs/toggle-check.svg
  src/components/.gitkeep
  src/components/bottom-navigation-bar.tsx
  src/components/gender-toggle-group.tsx
  src/components/header.tsx
  src/components/hospital-card.tsx
  src/components/ui/button.tsx
  src/components/ui/card.tsx
  src/components/ui/profile.tsx
  src/components/ui/toggle-group.tsx
  src/components/ui/toggle.tsx
  src/layouts/base-layout.tsx
  src/layouts/root-layout.tsx
  src/main.tsx
  src/routes/design-system.tsx
  src/styles/globals.css
  src/utils/.gitkeep
  src/utils/cn.ts
  tailwind.config.js
  vercel.json
Labels: enhancement

#12 fix: hover 상태 스타일 제거
  src/components/ui/button.tsx
  src/components/ui/toggle.tsx
Labels: bug

#15 feat: 진단 페이지 퍼블리싱
  eslint.config.js
  package.json
  pnpm-lock.yaml
  src/assets/images/arm-hand.png
  src/assets/images/face.png
  src/assets/images/head.png
  src/assets/images/leg-foot.png
  src/assets/images/neck-chest.png
  src/assets/images/pelvis.png
  src/assets/images/stomach.png
  src/assets/images/waist.png
  src/components/body-part-toggle.tsx
  src/components/etc-toggle.tsx
  src/components/ui/toggle.tsx
  src/constants/bodyparts.ts
  src/layouts/base-layout.tsx
  src/layouts/header-layout.tsx
  src/layouts/root-layout.tsx
  src/main.tsx
  src/routes/health-diary.tsx
Labels: enhancement

#16 docs: update readme.md
  README.md
Labels: documentation

#19 feat: 메인 페이지 퍼블리싱하기
  src/assets/images/chart.png
  src/assets/images/clipboard.png
  src/assets/images/magic-wand.png
  src/routes/root.tsx
Labels: enhancement

#21 feat: 온보딩 퍼블리싱하기
  src/assets/images/onboarding-1.png
  src/assets/images/onboarding-2.png
  src/assets/images/onboarding-3.png
  src/routes/onboarding-1.tsx
  src/routes/onboarding-2.tsx
  src/routes/onboarding-3.tsx
Labels: enhancement

#8 feat: 랜딩, 로그인, 서베이 페이지 UI 구현
  src/assets/images/gray-song.png
  src/assets/images/greeting-gliter.png
  src/assets/images/greeting-heart.png
  src/assets/images/greeting-lightning.png
  src/assets/images/greeting-rocket.png
  src/assets/images/greeting-search.png
  src/assets/images/greeting-song.png
  src/assets/images/greeting-star.png
  src/assets/images/landing-song.png
  src/assets/svgs/greeting-speech-bubble.svg
  src/assets/svgs/kakao.svg
  src/assets/svgs/landing-logo.svg
  src/assets/svgs/login-logo.svg
  src/components/etc-toggle.tsx
  src/components/gender-toggle-group.tsx
  src/main.tsx
  src/routes/greeting.tsx
  src/routes/landing.tsx
  src/routes/login.tsx
  src/routes/survey/input-birth-date.tsx
  src/routes/survey/select-gender.tsx
  src/routes/survey/select-medical-conditions.tsx
  src/routes/survey/survey.tsx
Labels: enhancement

#17 feat: 내 건강 기록 페이지 UI 구현하기
  src/assets/images/crying-song.png
  src/assets/images/warning.png
  src/assets/svgs/alert.svg
  src/main.tsx
  src/routes/monthly-health-history.tsx
  src/routes/my-health-change.tsx
  src/routes/my-health-history.tsx
  src/routes/settings.tsx
Labels: enhancement

#26 feat: add favicon & site.webmanifest
  public/android-chrome-192x192.png
  public/android-chrome-512x512.png
  public/apple-touch-icon.png
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon.ico
  public/site.webmanifest
Labels: enhancement

#27 feat: QA 디자인 수정
  src/components/header.tsx
  src/routes/my-health-history.tsx
  src/routes/onboarding-1.tsx
  src/routes/onboarding-2.tsx
  src/routes/onboarding-3.tsx
  src/routes/root.tsx
  src/routes/settings.tsx
  src/routes/survey/select-gender.tsx
Labels: enhancement

#28 fix: index.html에 favicon, webmanifest 등록하기, 디바이스 이슈 해결
  index.html
  public/site.webmanifest
  src/routes/health-diary.tsx
Labels: bug

#29 feat: 진단 결과 페이지 퍼블리싱
  eslint.config.js
  index.html
  package.json
  pnpm-lock.yaml
  src/assets/svgs/clip.svg
  src/assets/svgs/search.svg
  src/components/diagnose-markdown-renderer.tsx
  src/components/hospital-card.tsx
  src/components/ui/button.tsx
  src/components/ui/card.tsx
  src/main.tsx
  src/routes/design-system.tsx
  src/routes/diagnose-result.tsx
  src/routes/hospital.tsx
  tailwind.config.js
  tsconfig.app.json
Labels: enhancement

#30 feat: API 인스턴스 생성 및 라우팅 권한 제어
  package.json
  pnpm-lock.yaml
  src/api/instans.ts
  src/env.d.ts
  src/main.tsx
  src/routes/error.tsx
Labels: enhancement

#32 fix: add pnpm lock to .gitignore
  .gitignore
  pnpm-lock.yaml
Labels: bug

#33 fix: remove preinstall script from package.json
  package.json
Labels: bug

#35 refactor: change onboarding using carousel
  package.json
  src/main.tsx
  src/routes/on-board.tsx
  src/routes/onboarding-1.tsx
  src/routes/onboarding-2.tsx
  src/routes/onboarding-3.tsx
Labels: enhancement

#42 feat: update DiagnoseMarkdownRenderer to support custom components
  src/components/diagnose-markdown-renderer.tsx
  src/main.tsx
  src/routes/error.tsx
Labels: enhancement

#46 refactor: optimize toggle behavior and add loading state
  src/components/etc-toggle.tsx
  src/routes/health-diary.tsx
Labels: enhancement

#47 feat: add navigation functionality to MyHealthHistory buttons
  src/routes/my-health-history.tsx
Labels: enhancement
